### ISSUE TITLE
[Question] Solution to retirement of connectors within Teams?

### ISSUE THREAD

**Issue by ryanbuening** [MaceWindu/Seq.App.Teams.AdaptiveCard#15]
Hello - Will this application be able to work with the retirement of connectors in Teams? We are currently using `Seq.App.Teams`, but it appears that application will no longer work within a few months. Related ticket [here](https://github.com/AntoineGa/Seq.App.Teams/issues/47).

**Comment by MaceWindu** [comment]
Looks like MS at their best. Never stop being bag of dicks...

**Comment by MaceWindu** [comment]
Will check what we can do here

**Comment by MaceWindu** [comment]
As of now I don't observe any notifications like you posted in linked issue for events from this application, so taking into account how illegible the article from MS I would wait and see how it will develop.

**Comment by ryanbuening** [comment]
@MaceWindu I am also not seeing the `Action required` message when using `Seq.App.Teams.AdaptiveCard` which is good. 👍

However, I see the following in Teams when the Seq alert is triggered:

![image](https://github.com/MaceWindu/Seq.App.Teams.AdaptiveCard/assets/812974/8d2f4edf-3266-4dfd-b885-6ff0ea84f89f)

Is this possibly because I have not specified certain settings or a template?

**Comment by MaceWindu** [comment]
Could you try to setup it using Incoming Webhook (which we use now)? Never tried it with Workflow.

I have impression that currently only HTML webhooks are affected by retirement notification. Wether it will affect AdaptiveCard webhook this app use is not clear from MS article.

**Comment by MaceWindu** [comment]
Another option you could try and I will appreciate it is to specify template in app settings explicitly and play with versions. Template code is here https://github.com/MaceWindu/Seq.App.Teams.AdaptiveCard/blob/master/src/Seq.App.Teams.AdaptiveCard/Resources/default-template.json

try to change 1.5 version to 1.6

**Comment by MaceWindu** [comment]
It would be funny (not really) if powerapps support only 1.3 : https://powerusers.microsoft.com/t5/General-Power-Automate/We-re-sorry-this-card-couldn-t-be-displayed-version-1-5/td-p/2031138

as it probably will not work with current template

**Comment by ryanbuening** [comment]
With Workflows, 1.3 worked 👍. 1.6 did not. 👎

I do not see the option to Manage channels to add an Incoming Webhook in Teams at the moment. I'm assuming this is a permissions thing I would need to get access to.

**Comment by MaceWindu** [comment]
Thanks! Will verify we don't use anything unsupported by 1.3 and release compatible version later (probably next week).

To setup webhook in Teams 2 you need to go to channel settings and edit connectors:
![image](https://github.com/MaceWindu/Seq.App.Teams.AdaptiveCard/assets/1099238/5c25a4aa-8cbc-4e01-bbd7-02fd75aa05a0)

Also could you provide notes how to setup it using workflow so I can test/update readme

**Comment by MaceWindu** [comment]
Ok, our default template doesn't use anything that require version 1.4 or 1.5 so we just need to change version in template. Still could affect users with custom templates if they use anything from those versions and want to use Workflow

**Comment by ryanbuening** [comment]
> To setup webhook in Teams 2 you need to go to channel settings and edit connectors

Yep, I just don't have access. However, it appears webhooks/connectors will be going away as referenced in the Microsoft post. They just haven't updated the docs yet. See [here](https://github.com/MicrosoftDocs/msteams-docs/issues/11222) and [here](https://github.com/MicrosoftDocs/msteams-docs/issues/11225). 

It appears Workflows are the path forward.

**Comment by tormodfj** [comment]
I arrived here under the exact same circumstances as OP, and switching the Adaptive Card version to `1.3` was the solution for us as well. 

I would definitely categorize this as a Teams/Workflows bug though, as the documentation [clearly states](https://learn.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference#adaptive-card:~:text=Note-,Teams%20platform%20supports%20v1.5%20or%20earlier%20of%20Adaptive%20Card%20features,-for%20bot%20sent) that the Teams Platform supports version `1.5`. Nevertheless, unless MS fixes this on their part, you should probably expect more people with this issue as we approach the date of retirement of connectors in Teams.

**Comment by MaceWindu** [comment]
@tormodfj , yes, Teams support 1.5 and we currently use this version with webhook. But Power(less) Automate (unnecessary new mediator between event source and Teams) doesn't. I plan to release update today, so users don't need to edit template in settings to use this app with workflows...

**Comment by MaceWindu** [comment]
2.1.0 released with default template schema version lowered to 1.3

**Comment by ryanbuening** [comment]
Thanks @MaceWindu! Let me know if there is anything else you would like me to test.

My plan is to convert all of our existing `Seq.App.Teams` alerts to use `Seq.App.Teams.AdaptiveCard`.

**Comment by MaceWindu** [comment]
@ryanbuening would appreciate if somebody could provide instructions how to make it work with private channels so we can add it to readme. Tried to click around and gave up for now

**Comment by ryanbuening** [comment]
Wish I could help, but I don't have access to create Teams and Channels at my company. However, the [comments](https://devblogs.microsoft.com/microsoft365dev/retirement-of-office-365-connectors-within-microsoft-teams/#comments) from the Microsoft retirement article might shed some light on this:

Maybe you could give setting the `Post As` setting to `User` a try?

![image](https://github.com/user-attachments/assets/cc0a6f58-c016-499c-892e-29b9d7dbc69d)

**Comment by MaceWindu** [comment]
👍  THAT actually worked. Will update readme
